export interface LabExperiment {
  id: string;
  title: string;
  status: "Experimental" | "Preview" | "Beta" | "Research";
  category: string;
  badge: string;
  description: string;
  releaseDate: string;
  tags: string[];
  features: string[];
}

export const LABS_EXPERIMENTS: LabExperiment[] = [
  {
    id: "direct-lake-memory-estimator",
    title: "Direct Lake Memory & Paging Estimator",
    status: "Experimental",
    category: "Power BI Performance",
    badge: "v3.1 Preview",
    description: "Calculates RAM footprint and memory paging limits when hosting massive 100GB+ tables in Direct Lake mode on F64+ capacities.",
    releaseDate: "July 2026",
    tags: ["Direct Lake", "Memory Paging", "F64+", "VertiPaq"],
    features: [
      "Simulates column-level VertiPaq compression ratio",
      "Estimates fallback risk to DirectQuery mode",
      "Calculates peak RAM requirements under multi-user concurrency"
    ]
  },
  {
    id: "fabric-copilot-token-calculator",
    title: "Fabric Copilot AI Compute Impact Engine",
    status: "Preview",
    category: "AI & FinOps",
    badge: "Build 2026 Special",
    description: "Estimates additional CU consumption generated by continuous Copilot queries across Spark notebook generation, DAX creation, and Data Factory orchestrations.",
    releaseDate: "June 2026",
    tags: ["Copilot", "GenAI", "F64", "Token Estimator"],
    features: [
      "Calculates CU consumption per 10,000 Copilot prompt tokens",
      "Analyzes F64 vs F128 Copilot burst capacity headroom",
      "Recommends throttling mitigation strategies for AI workloads"
    ]
  },
  {
    id: "mirroring-egress-calculator",
    title: "Database Mirroring & Real-Time Egress Cost Calculator",
    status: "Beta",
    category: "OneLake Storage",
    badge: "v3.0 Lab",
    description: "Estimates continuous CDC mirroring costs from Snowflake, Azure SQL, and Cosmos DB into OneLake Delta Parquet format.",
    releaseDate: "May 2026",
    tags: ["Mirroring", "CDC", "OneLake", "Egress"],
    features: [
      "Models continuous change data capture (CDC) compute impact",
      "Calculates OneLake landing zone storage overhead",
      "Estimates cross-cloud egress pricing for multi-cloud data lakes"
    ]
  },
  {
    id: "fabric-feature-radar-2026",
    title: "Microsoft Fabric 2026 Feature & Roadmap Radar",
    status: "Research",
    category: "Platform Strategy",
    badge: "Community Exclusive",
    description: "Deep dive technical analysis of recently announced Microsoft Build features, public previews, and expected SLA updates.",
    releaseDate: "July 2026",
    tags: ["Microsoft Build", "Roadmap", "DP-600", "DP-700"],
    features: [
      "Impact analysis of upcoming Fabric Capacity API updates",
      "Breakdown of new Spark 3.5 runtime optimizations",
      "OneLake shortcut security enhancement breakdown"
    ]
  }
];
